### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by nunojesus** [cppocl/portable#4]
Hello, just want to know if you want some ideas for a logotype design for this project.
Im a graphic designer and I have been contributing to opensorce projects, so if you want some help just say it.

Greetings

**Comment by colinrg** [comment]
Thanks for the offer, but currently don't have a need for graphical resources.
Actually my projects almost don't get a following, so this is not an issue for me.

**Comment by nunojesus** [comment]
Ok. no problem.
